<?php

namespace AppBundle\Repository;

/**
 * AreasDoConhecimentoTextoEmJornalOuRevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasDoConhecimentoTextoEmJornalOuRevistaRepository extends \Doctrine\ORM\EntityRepository
{
}
