<?php

namespace AppBundle\Repository;

/**
 * AreasDoConhecimentoTrabalhoEmEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasDoConhecimentoTrabalhoEmEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
