<?php

namespace AppBundle\Repository;

/**
 * AreasDoConhecimentoCapituloDeLivroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasDoConhecimentoCapituloDeLivroRepository extends \Doctrine\ORM\EntityRepository
{
}
