<?php

namespace AppBundle\Repository;

/**
 * AreasDoConhecimentoArtigoAceitoParaPublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasDoConhecimentoArtigoAceitoParaPublicacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
