<?php

namespace AppBundle\Repository;

/**
 * AreasDoConhecimentoArtigoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasDoConhecimentoArtigoRepository extends \Doctrine\ORM\EntityRepository
{
}
