<?php

namespace AppBundle\Repository;

/**
 * ArtigosPublicadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtigosPublicadosRepository extends \Doctrine\ORM\EntityRepository
{
}
