<?php

namespace AppBundle\Repository;

/**
 * ArtigoAceitoParaPublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtigoAceitoParaPublicacaoRepository extends \Doctrine\ORM\EntityRepository
{

}
