<?php

namespace AppBundle\Repository;

/**
 * AutoresTrabalhosEmEventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoresTrabalhosEmEventosRepository extends \Doctrine\ORM\EntityRepository
{
}
