<?php

namespace AppBundle\Repository;

/**
 * AutoresArtigoAceitoParaPublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoresArtigoAceitoParaPublicacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
