<?php

namespace AppBundle\Repository;

/**
 * AutoresCapituloDeLivroPublicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoresCapituloDeLivroPublicadoRepository extends \Doctrine\ORM\EntityRepository
{
}
