<?php

namespace AppBundle\Repository;

/**
 * AutoresTextoEmJornalOuRevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoresTextoEmJornalOuRevistaRepository extends \Doctrine\ORM\EntityRepository
{
}
