<?php

namespace AppBundle\Repository;

/**
 * CapituloDeLivroPublicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapituloDeLivroPublicadoRepository extends \Doctrine\ORM\EntityRepository
{
}
