<?php

namespace AppBundle\Repository;

/**
 * FormacaoAcademicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormacaoAcademicaRepository extends \Doctrine\ORM\EntityRepository
{
}
