<?php

namespace AppBundle\Repository;

/**
 * GrauDeFormacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrauDeFormacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
