<?php

namespace AppBundle\Repository;

/**
 * PalavrasChaveTextoEmJornalOuRevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalavrasChaveTextoEmJornalOuRevistaRepository extends \Doctrine\ORM\EntityRepository
{
}
