<?php

namespace AppBundle\Repository;

/**
 * PalavrasChaveArtigosPublicadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalavrasChaveArtigosPublicadosRepository extends \Doctrine\ORM\EntityRepository
{
}
