<?php

namespace AppBundle\Repository;

/**
 * PalavrasChaveCapituloDeLivroPublicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalavrasChaveCapituloDeLivroPublicadoRepository extends \Doctrine\ORM\EntityRepository
{
}
