<?php

namespace AppBundle\Repository;

/**
 * PalavrasChaveTrabalhoEmEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalavrasChaveTrabalhoEmEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
