<?php

namespace AppBundle\Repository;

/**
 * PalavrasChaveArtigoAceitoParaPublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalavrasChaveArtigoAceitoParaPublicacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
