<?php

namespace AppBundle\Repository;

/**
 * SetoresDeAtividadeArtigosPublicadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetoresDeAtividadeArtigosPublicadosRepository extends \Doctrine\ORM\EntityRepository
{
}
