<?php

namespace AppBundle\Repository;

/**
 * SetoresDeAtividadeTrabalhoEmEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetoresDeAtividadeTrabalhoEmEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
