<?php

namespace AppBundle\Repository;

/**
 * SetoresDeAtividadeTextoEmJornalOuRevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetoresDeAtividadeTextoEmJornalOuRevistaRepository extends \Doctrine\ORM\EntityRepository
{
}
