<?php

namespace AppBundle\Repository;

/**
 * SetoresDeAtividadeCapituloDeLivroPublicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetoresDeAtividadeCapituloDeLivroPublicadoRepository extends \Doctrine\ORM\EntityRepository
{
}
