<?php

namespace AppBundle\Repository;

/**
 * SetoresDeAtividadeArtigoAceitoParaPublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetoresDeAtividadeArtigoAceitoParaPublicacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
