<?php

namespace AppBundle\Repository;

/**
 * TrabalhosEmEventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabalhosEmEventosRepository extends \Doctrine\ORM\EntityRepository
{
}
